spring:
  jwt:
    secret: askdfjlskdfjsldkfjsldkfjslfkjsldfkjsldfkjsldfkjsldfkjsdflksjdflkjsfaisdgjoaigj

  datasource:
    url: jdbc:h2:tcp://localhost/~/morningbuddies
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace