spring:
  profiles:
    active: dev
  jwt:
    secret: ${JWT_SECRET}

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org:
      springframework:
        web:
          socket: DEBUG
    com:
      morningbuddies: DEBUG

aws:
  access_key: ${AWS_S3_ACCESS_KEY}
  secret_key: ${AWS_S3_SECRET_KEY}
  s3:
    bucket_name: ${AWS_S3_BUCKET_NAME}
    url: ${AWS_S3_URL}
  region: ${AWS_REGION}

openai:
  api:
    key: ${OPENAI_API_KEY}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
